use regex::Regex;
use std::path::PathBuf;

/// A single matching location within a file.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FileMatch {
    pub path: String,
    pub line_number: usize,
    pub line_content: String,
    /// Whether this match is in a file detected as auto-generated.
    #[serde(default)]
    pub in_generated_file: bool,
    /// Whether this match is inside a `#[cfg(test)]` module.
    #[serde(default)]
    pub in_test_code: bool,
}

/// Result of scanning an intermediate crate for references to a fat dependency.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ScanResult {
    pub fat_crate_name: String,
    /// All names that were searched for (original + aliases).
    #[serde(default)]
    pub searched_names: Vec<String>,
    pub ref_count: usize,
    pub file_matches: Vec<FileMatch>,
    pub files_with_matches: usize,
    /// Number of matches found in auto-generated files.
    #[serde(default)]
    pub generated_file_refs: usize,
    /// Number of matches found inside `#[cfg(test)]` modules.
    #[serde(default)]
    pub test_only_refs: usize,
    /// Distinct API items used (e.g., "Regex::new", "from_u8").
    #[serde(default)]
    pub distinct_items: Vec<String>,
    /// True if the intermediate crate has `pub use <fat_dep>::*`.
    #[serde(default)]
    pub has_re_export_all: bool,
}

/// Detect test-only files by path convention (tests/, *_test.rs, test_*.rs).
fn is_test_file(path: &std::path::Path) -> bool {
    let path_str = path.to_string_lossy();
    if path_str.contains("/tests/") || path_str.contains("\\tests\\") {
        return true;
    }
    if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
        if name.ends_with("_test") || name.starts_with("test_") {
            return true;
        }
    }
    false
}

/// Heuristics to detect auto-generated source files.
fn is_generated_file(content: &str) -> bool {
    // Check first 10 lines for generation markers.
    for line in content.lines().take(10) {
        let lower = line.to_lowercase();
        if lower.contains("@generated")
            || lower.contains("this file was auto-generated")
            || lower.contains("this file is auto-generated")
            || lower.contains("automatically generated")
            || lower.contains("do not edit")
            || lower.contains("generated by")
            || lower.contains("auto-generated by")
            || lower.contains("this file has been auto-generated")
        {
            return true;
        }
    }
    false
}

/// Scan the given `.rs` files for references to `fat_crate_name`.
///
/// Uses lexical scanning with regex. Searches for:
/// - `use <crate>::...`
/// - `<crate>::...` in expressions
/// - `extern crate <crate>`
///
/// Also searches for any additional `aliases` (from Cargo.toml package renaming).
///
/// Skips single-line comments. Not perfect, but fast and good enough.
pub fn scan_files(rs_files: &[PathBuf], fat_crate_name: &str) -> ScanResult {
    scan_files_with_aliases(rs_files, fat_crate_name, &[])
}

pub fn scan_files_with_aliases(
    rs_files: &[PathBuf],
    fat_crate_name: &str,
    aliases: &[String],
) -> ScanResult {
    // Cargo normalizes hyphens to underscores in Rust code.
    let normalized = fat_crate_name.replace('-', "_");

    // Collect all names to search for.
    let mut names: Vec<String> = vec![normalized.clone()];
    for alias in aliases {
        let alias_norm = alias.replace('-', "_");
        if !names.contains(&alias_norm) {
            names.push(alias_norm);
        }
    }

    // Build combined pattern for all names.
    let mut pattern_parts = Vec::new();
    for name in &names {
        let escaped = regex::escape(name);
        pattern_parts.push(format!(r"\b{escaped}::"));
        pattern_parts.push(format!(r"\buse\s+{escaped}\b"));
        pattern_parts.push(format!(r"\bextern\s+crate\s+{escaped}\b"));
    }

    // Add macro/attribute patterns for crates commonly used via proc-macros,
    // derive macros, or attribute macros rather than explicit `use` imports.
    // Without these, the scanner reports 0 refs for macro-heavy crates.
    add_macro_patterns(&mut pattern_parts, fat_crate_name, &names);

    let combined = pattern_parts
        .iter()
        .map(|p| format!("(?:{p})"))
        .collect::<Vec<_>>()
        .join("|");
    let re = Regex::new(&combined).expect("valid regex");

    // Build a pattern to detect `pub use <name>::*` re-exports.
    let re_export_patterns: Vec<String> = names
        .iter()
        .map(|name| format!(r"pub\s+use\s+{}::\*", regex::escape(name)))
        .collect();
    let re_export_combined = re_export_patterns.join("|");
    let re_export_re = Regex::new(&re_export_combined).expect("valid regex");

    let mut file_matches = Vec::new();
    let mut files_with_matches = 0;
    let mut generated_file_refs = 0;
    let mut test_only_refs = 0;
    let mut has_re_export_all = false;

    for path in rs_files {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let generated = is_generated_file(&content);
        let in_test_file = is_test_file(path);
        let mut found_in_file = false;
        // Track whether we're inside a `#[cfg(test)]` module by watching
        // for the attribute and then tracking brace depth.
        let mut in_test_mod = in_test_file;
        let mut test_brace_depth: Option<usize> = if in_test_file { Some(0) } else { None };
        let mut brace_depth: usize = 0;

        for (line_idx, line) in content.lines().enumerate() {
            let trimmed = line.trim_start();

            // Track #[cfg(test)] module entry.
            if trimmed.starts_with("#[cfg(test)]") {
                // The next `mod` block or the following braced block is test code.
                test_brace_depth = Some(brace_depth);
            }

            // Update brace depth.
            for ch in line.chars() {
                match ch {
                    '{' => brace_depth += 1,
                    '}' => {
                        brace_depth = brace_depth.saturating_sub(1);
                        // If we close back to the depth where #[cfg(test)] started,
                        // we've exited the test module.
                        if let Some(test_depth) = test_brace_depth {
                            if brace_depth <= test_depth && !in_test_file {
                                in_test_mod = false;
                                test_brace_depth = None;
                            }
                        }
                    }
                    _ => {}
                }
            }

            // If we just entered a block after #[cfg(test)], mark as in test.
            if let Some(test_depth) = test_brace_depth {
                if brace_depth > test_depth {
                    in_test_mod = true;
                }
            }

            // Skip single-line comments.
            if trimmed.starts_with("//") {
                continue;
            }

            // Check for `pub use <dep>::*` re-export.
            if !has_re_export_all && re_export_re.is_match(line) {
                has_re_export_all = true;
            }

            if re.is_match(line) {
                found_in_file = true;
                if generated {
                    generated_file_refs += 1;
                }
                if in_test_mod {
                    test_only_refs += 1;
                }
                file_matches.push(FileMatch {
                    path: path.display().to_string(),
                    line_number: line_idx + 1,
                    line_content: line.trim().to_string(),
                    in_generated_file: generated,
                    in_test_code: in_test_mod,
                });
            }
        }

        if found_in_file {
            files_with_matches += 1;
        }
    }

    let ref_count = file_matches.len();
    let distinct_items = extract_distinct_items(&file_matches, &names);
    ScanResult {
        fat_crate_name: fat_crate_name.to_string(),
        searched_names: names,
        ref_count,
        file_matches,
        files_with_matches,
        generated_file_refs,
        test_only_refs,
        distinct_items,
        has_re_export_all,
    }
}

/// Relativize a path for display purposes, replacing the cargo registry prefix
/// with `~/.cargo/registry/src/.../<crate>/`.
pub fn display_path(path: &str) -> String {
    if let Some(idx) = path.find(".cargo/registry/src/") {
        let home_prefix = &path[..idx];
        let rest = &path[idx + ".cargo/registry/src/".len()..];
        // Strip the registry hash directory.
        if let Some(slash_idx) = rest.find('/') {
            return format!(
                "{}/.cargo/registry/src/.../{}",
                home_prefix.trim_end_matches('/'),
                &rest[slash_idx + 1..]
            );
        }
    }
    path.to_string()
}

/// Crates that are commonly used via proc-macro derives, attribute macros,
/// or macro invocations (`crate_name!()`) rather than explicit `use` imports.
/// The scanner adds extra patterns for these to reduce false positives.
const MACRO_CRATES: &[(&str, &[&str])] = &[
    // Derive macros: #[derive(Serialize, Deserialize)]
    ("serde", &[r"#\[derive\([^)]*\b(Serialize|Deserialize)\b"]),
    (
        "serde_json",
        &[
            r"\bserde_json!\b",
            r"\bjson!\b",
            r#"serde_json::from_"#,
            r#"serde_json::to_"#,
        ],
    ),
    (
        "clap",
        &[
            r"#\[derive\([^)]*\b(Parser|Args|Subcommand|ValueEnum)\b",
            r"#\[command\b",
            r"#\[arg\b",
        ],
    ),
    ("thiserror", &[r"#\[derive\([^)]*\bError\b"]),
    (
        "tokio",
        &[r"#\[tokio::", r"tokio::spawn\b", r"tokio::select!\b"],
    ),
    (
        "tracing",
        &[
            r"\btracing::(info|debug|warn|error|trace|instrument)\b",
            r"#\[instrument\b",
            r"#\[tracing::instrument\b",
            r"\b(info|debug|warn|error|trace)!\(",
        ],
    ),
    ("log", &[r"\b(info|debug|warn|error|trace)!\("]),
    (
        "anyhow",
        &[
            r"\banyhow!\(",
            r"\bbail!\(",
            r"\bensure!\(",
            r"\bResult<",
            r"\banyhow::Result\b",
            r"\bContext\b",
        ],
    ),
    ("async_trait", &[r"#\[async_trait\b"]),
    (
        "strum",
        &[r"#\[derive\([^)]*\b(EnumString|Display|EnumIter|IntoStaticStr)\b"],
    ),
    (
        "derive_more",
        &[r"#\[derive\([^)]*\b(From|Into|Display|Deref|Constructor)\b"],
    ),
];

/// Crates that are typically activated via `#[global_allocator]` static declarations
/// rather than `use` imports.
const ALLOCATOR_CRATES: &[(&str, &str)] = &[
    ("mimalloc", "MiMalloc"),
    ("tikv-jemallocator", "Jemalloc"),
    ("jemallocator", "Jemalloc"),
    ("snmalloc-rs", "SnMalloc"),
];

/// Add extra regex patterns for crates commonly used through macros/derives/attributes
/// rather than explicit `use` imports.
fn add_macro_patterns(patterns: &mut Vec<String>, fat_crate_name: &str, names: &[String]) {
    let normalized = fat_crate_name.replace('-', "_");

    // Check known macro crates.
    for (crate_name, extra_patterns) in MACRO_CRATES {
        if normalized == crate_name.replace('-', "_")
            || names.iter().any(|n| *n == crate_name.replace('-', "_"))
        {
            for p in *extra_patterns {
                patterns.push(p.to_string());
            }
        }
    }

    // Check allocator crates: look for `#[global_allocator]` + type name.
    for (crate_name, type_name) in ALLOCATOR_CRATES {
        if normalized == crate_name.replace('-', "_")
            || names.iter().any(|n| *n == crate_name.replace('-', "_"))
        {
            patterns.push(r"#\[global_allocator\]".to_string());
            patterns.push(format!(r"\b{type_name}\b"));
        }
    }
}

/// Extract distinct API items from matched lines.
/// e.g., `use idna::domain_to_ascii` -> "domain_to_ascii"
/// e.g., `cached::UnboundCache` -> "UnboundCache"
fn extract_distinct_items(matches: &[FileMatch], crate_names: &[String]) -> Vec<String> {
    let mut items = std::collections::HashSet::new();

    for m in matches {
        let line = &m.line_content;

        for name in crate_names {
            // Match patterns like `name::Item` or `name::{Item1, Item2}`
            let prefix = format!("{name}::");
            for (idx, _) in line.match_indices(&prefix) {
                let after = &line[idx + prefix.len()..];

                if after.starts_with('{') {
                    // use crate::{A, B, C}
                    if let Some(close) = after.find('}') {
                        for item in after[1..close].split(',') {
                            let item = item.trim().split("::").next().unwrap_or("").trim();
                            if !item.is_empty() && item != "*" {
                                items.insert(item.to_string());
                            }
                        }
                    }
                } else {
                    // use crate::Item or crate::Item::method
                    let item: String = after
                        .chars()
                        .take_while(|c| c.is_alphanumeric() || *c == '_')
                        .collect();
                    if !item.is_empty() && item != "*" {
                        items.insert(item);
                    }
                }
            }
        }
    }

    let mut sorted: Vec<String> = items.into_iter().collect();
    sorted.sort();
    sorted
}
