use regex::Regex;
use std::path::PathBuf;

/// A single matching location within a file.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FileMatch {
    pub path: String,
    pub line_number: usize,
    pub line_content: String,
    /// Whether this match is in a file detected as auto-generated.
    #[serde(default)]
    pub in_generated_file: bool,
}

/// Result of scanning an intermediate crate for references to a fat dependency.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ScanResult {
    pub fat_crate_name: String,
    /// All names that were searched for (original + aliases).
    #[serde(default)]
    pub searched_names: Vec<String>,
    pub ref_count: usize,
    pub file_matches: Vec<FileMatch>,
    pub files_with_matches: usize,
    /// Number of matches found in auto-generated files.
    #[serde(default)]
    pub generated_file_refs: usize,
    /// Distinct API items used (e.g., "Regex::new", "from_u8").
    #[serde(default)]
    pub distinct_items: Vec<String>,
    /// True if the intermediate crate has `pub use <fat_dep>::*`.
    #[serde(default)]
    pub has_re_export_all: bool,
}

/// Heuristics to detect auto-generated source files.
fn is_generated_file(content: &str) -> bool {
    // Check first 10 lines for generation markers.
    for line in content.lines().take(10) {
        let lower = line.to_lowercase();
        if lower.contains("@generated")
            || lower.contains("this file was auto-generated")
            || lower.contains("this file is auto-generated")
            || lower.contains("automatically generated")
            || lower.contains("do not edit")
            || lower.contains("generated by")
            || lower.contains("auto-generated by")
            || lower.contains("this file has been auto-generated")
        {
            return true;
        }
    }
    false
}

/// Scan the given `.rs` files for references to `fat_crate_name`.
///
/// Uses lexical scanning with regex. Searches for:
/// - `use <crate>::...`
/// - `<crate>::...` in expressions
/// - `extern crate <crate>`
///
/// Also searches for any additional `aliases` (from Cargo.toml package renaming).
///
/// Skips single-line comments. Not perfect, but fast and good enough.
pub fn scan_files(rs_files: &[PathBuf], fat_crate_name: &str) -> ScanResult {
    scan_files_with_aliases(rs_files, fat_crate_name, &[])
}

pub fn scan_files_with_aliases(
    rs_files: &[PathBuf],
    fat_crate_name: &str,
    aliases: &[String],
) -> ScanResult {
    // Cargo normalizes hyphens to underscores in Rust code.
    let normalized = fat_crate_name.replace('-', "_");

    // Collect all names to search for.
    let mut names: Vec<String> = vec![normalized.clone()];
    for alias in aliases {
        let alias_norm = alias.replace('-', "_");
        if !names.contains(&alias_norm) {
            names.push(alias_norm);
        }
    }

    // Build combined pattern for all names.
    let mut pattern_parts = Vec::new();
    for name in &names {
        let escaped = regex::escape(name);
        pattern_parts.push(format!(r"\b{escaped}::"));
        pattern_parts.push(format!(r"\buse\s+{escaped}\b"));
        pattern_parts.push(format!(r"\bextern\s+crate\s+{escaped}\b"));
    }

    let combined = pattern_parts
        .iter()
        .map(|p| format!("(?:{p})"))
        .collect::<Vec<_>>()
        .join("|");
    let re = Regex::new(&combined).expect("valid regex");

    // Build a pattern to detect `pub use <name>::*` re-exports.
    let re_export_patterns: Vec<String> = names
        .iter()
        .map(|name| format!(r"pub\s+use\s+{}::\*", regex::escape(name)))
        .collect();
    let re_export_combined = re_export_patterns.join("|");
    let re_export_re = Regex::new(&re_export_combined).expect("valid regex");

    let mut file_matches = Vec::new();
    let mut files_with_matches = 0;
    let mut generated_file_refs = 0;
    let mut has_re_export_all = false;

    for path in rs_files {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let generated = is_generated_file(&content);
        let mut found_in_file = false;

        for (line_idx, line) in content.lines().enumerate() {
            let trimmed = line.trim_start();

            // Skip single-line comments.
            if trimmed.starts_with("//") {
                continue;
            }

            // Check for `pub use <dep>::*` re-export.
            if !has_re_export_all && re_export_re.is_match(line) {
                has_re_export_all = true;
            }

            if re.is_match(line) {
                found_in_file = true;
                if generated {
                    generated_file_refs += 1;
                }
                file_matches.push(FileMatch {
                    path: path.display().to_string(),
                    line_number: line_idx + 1,
                    line_content: line.trim().to_string(),
                    in_generated_file: generated,
                });
            }
        }

        if found_in_file {
            files_with_matches += 1;
        }
    }

    let ref_count = file_matches.len();
    let distinct_items = extract_distinct_items(&file_matches, &names);
    ScanResult {
        fat_crate_name: fat_crate_name.to_string(),
        searched_names: names,
        ref_count,
        file_matches,
        files_with_matches,
        generated_file_refs,
        distinct_items,
        has_re_export_all,
    }
}

/// Relativize a path for display purposes, replacing the cargo registry prefix
/// with `~/.cargo/registry/src/.../<crate>/`.
pub fn display_path(path: &str) -> String {
    if let Some(idx) = path.find(".cargo/registry/src/") {
        let home_prefix = &path[..idx];
        let rest = &path[idx + ".cargo/registry/src/".len()..];
        // Strip the registry hash directory.
        if let Some(slash_idx) = rest.find('/') {
            return format!(
                "{}/.cargo/registry/src/.../{}",
                home_prefix.trim_end_matches('/'),
                &rest[slash_idx + 1..]
            );
        }
    }
    path.to_string()
}

/// Extract distinct API items from matched lines.
/// e.g., `use idna::domain_to_ascii` -> "domain_to_ascii"
/// e.g., `cached::UnboundCache` -> "UnboundCache"
fn extract_distinct_items(matches: &[FileMatch], crate_names: &[String]) -> Vec<String> {
    let mut items = std::collections::HashSet::new();

    for m in matches {
        let line = &m.line_content;

        for name in crate_names {
            // Match patterns like `name::Item` or `name::{Item1, Item2}`
            let prefix = format!("{name}::");
            for (idx, _) in line.match_indices(&prefix) {
                let after = &line[idx + prefix.len()..];

                if after.starts_with('{') {
                    // use crate::{A, B, C}
                    if let Some(close) = after.find('}') {
                        for item in after[1..close].split(',') {
                            let item = item.trim().split("::").next().unwrap_or("").trim();
                            if !item.is_empty() && item != "*" {
                                items.insert(item.to_string());
                            }
                        }
                    }
                } else {
                    // use crate::Item or crate::Item::method
                    let item: String = after
                        .chars()
                        .take_while(|c| c.is_alphanumeric() || *c == '_')
                        .collect();
                    if !item.is_empty() && item != "*" {
                        items.insert(item);
                    }
                }
            }
        }
    }

    let mut sorted: Vec<String> = items.into_iter().collect();
    sorted.sort();
    sorted
}
